version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: randomcooking
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/data:/var/lib/postgresql/data
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d
